### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MCUnderground** [LostTeam/ClearChat#2]
@LostTeam/plugin-coders 

Can someone make onCommand so people can add banned words and remove them. Like /cc add *****
/cc remove *****

Im bad with config :/

**Comment by remotevase** [comment]
I am not too good with config, but I can help with that

**Comment by MCUnderground** [comment]
Thx

**Comment by jasonwynn10** [comment]
I'll help too

**Comment by jasonwynn10** [comment]
lol same, I just figured it out yesterday

**Comment by MCUnderground** [comment]
Thx tho 😂💪

**Comment by jasonwynn10** [comment]
sure

**Comment by ImagicalGamer** [comment]
I can add the config, xD took like 2 hours for me to figure out the config and now I want to add it to EVERYTHINGGG XD.

**Comment by ImagicalGamer** [comment]
Oops xD

**Comment by jasonwynn10** [comment]
...
